
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;
using MyLib.Services;

[assembly: EdmSchemaAttribute()]

namespace MyLib.Net.Tests
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities() : base("name=Entities", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(string connectionString) : base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<EFTestData> EFTestDatas
        {
            get
            {
                if ((_EFTestDatas == null))
                {
                    _EFTestDatas = base.CreateObjectSet<EFTestData>("EFTestDatas");
                }
                return _EFTestDatas;
            }
        }
        private ObjectSet<EFTestData> _EFTestDatas;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the EFTestDatas EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEFTestDatas(EFTestData eFTestData)
        {
            base.AddObject("EFTestDatas", eFTestData);
        }

        #endregion

    }
    

    #endregion

    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="TestDatabaseModel", Name="EFTestData")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class EFTestData : EntityObject, IRepoData
    {
        public System.Data.EntityKey PrimaryKey { get { return this.EntityKey; } }
        #region Factory Method
    
        /// <summary>
        /// Create a new EFTestData object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="timestamp">Initial value of the Timestamp property.</param>
        /// <param name="testString">Initial value of the TestString property.</param>
        public static EFTestData CreateEFTestData(global::System.Guid id, global::System.DateTime timestamp, global::System.String testString)
        {
            EFTestData eFTestData = new EFTestData();
            eFTestData.Id = id;
            eFTestData.Timestamp = timestamp;
            eFTestData.TestString = testString;
            return eFTestData;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime Timestamp
        {
            get
            {
                return _Timestamp;
            }
            set
            {
                OnTimestampChanging(value);
                ReportPropertyChanging("Timestamp");
                _Timestamp = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Timestamp");
                OnTimestampChanged();
            }
        }
        private global::System.DateTime _Timestamp;
        partial void OnTimestampChanging(global::System.DateTime value);
        partial void OnTimestampChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TestString
        {
            get
            {
                return _TestString;
            }
            set
            {
                OnTestStringChanging(value);
                ReportPropertyChanging("TestString");
                _TestString = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TestString");
                OnTestStringChanged();
            }
        }
        private global::System.String _TestString;
        partial void OnTestStringChanging(global::System.String value);
        partial void OnTestStringChanged();

        #endregion

    
    }

    #endregion

    
}
